import fs from 'fs';
const bankStatmentFile = fs.createReadStream('./scripts/bank_statement_1.pdf');

export const createStipData = {
    file: bankStatmentFile,
    file_name: 'bank_statement_1.pdf',
    file_type: 'application/pdf',
    stipulation_type_id: '1',
};

export const createDealData = {
    name_legal: 'Music Stores In Space',
    business_street_1: '72 N 12 W',
    business_street_2: '',
    business_city: 'New York',
    business_state: 'NY',
    business_zip_code: '10023',
    business_phone: '8887776666',
    business_industry_type: 'Retail',
    business_start_date: '2005-12-25',
    business_date_aquired: '2005-08-15',
    entity_type: 'CORPORATION',
    fein: '12-1231234',
    notes: 'Needs a decision within three days',
    first_name: 'Fred',
    last_name: 'Flintstone',
    owner_1_street_1: '123 Kitty cat trail',
    owner_1_street_2: '',
    owner_1_city: 'Centennial',
    owner_1_state: 'CO',
    owner_1_zip_code: '80016',
    owner_1_ssn: '123-12-1234',
    owner_1_dob: '2000-12-13',
    owner_1_percent_ownership: '33',
    owner_1_phone: '1233211234',
    owner_1_email: 'fred@test.com',
    owner_2_first_name: 'George',
    owner_2_last_name: 'Stevenson',
    owner_2_street_1: '777 S Main St',
    owner_2_street_2: '',
    owner_2_city: 'Halfmoon',
    owner_2_state: 'NY',
    owner_2_zip_code: '12065',
    owner_2_ssn: '999-99-9999',
    owner_2_dob: '1955-11-17',
    owner_2_percent_ownership: '33',
    owner_2_phone: '5555555555',
    owner_2_email: 'george@test.com',
    owner_3_first_name: 'Kelsey',
    owner_3_last_name: 'MacKenzie',
    owner_3_street_1: '1243 E Graham Ave',
    owner_3_street_2: '',
    owner_3_city: 'Greenwich',
    owner_3_state: 'CT',
    owner_3_zip_code: '06807',
    owner_3_ssn: '444-44-3333',
    owner_3_dob: '1985-02-22',
    owner_3_percent_ownership: '33',
    owner_3_phone: '9098881234',
    owner_3_email: 'kelsey@test.com',
    amount_requested: 100000,
    use_of_funds: 'Buying more banjos',
    file_1: bankStatmentFile,
    file_1_name: 'bank_statement_1.pdf',
    file_1_type: 'application/pdf',
    file_1_stipulation_type_id: '1',
};
